### ISSUE TITLE
Running rake db:setup fails

### ISSUE THREAD

**Issue by markediez** [dssit/marchand#28]
Remove your current db/development.sql
Run `rake db:setup`

You should get the error below
```console
-- create_table("keyword_assignments", {:primary_key=>["sid", "kid"], :force=>:cascade})
rake aborted!
ArgumentError: Index name 'sqlite_autoindex_keyword_assignments_1' on table 'keyword_assignments' already exists
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:1145:in `add_index_options'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:712:in `add_index'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:282:in `block in create_table'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:281:in `each'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:281:in `create_table'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/migration.rb:846:in `block in method_missing'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `block in say_with_time'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `say_with_time'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/migration.rb:835:in `method_missing'
/Users/MarkDiez/Documents/Projects/DSSIT/history-project/db/schema.rb:58:in `block in <top (required)>'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/schema.rb:48:in `instance_eval'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/schema.rb:48:in `define'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/schema.rb:44:in `define'
/Users/MarkDiez/Documents/Projects/DSSIT/history-project/db/schema.rb:13:in `<top (required)>'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `block in load'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:223:in `load_schema'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:253:in `block in load_schema_current'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:292:in `block in each_current_configuration'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:291:in `each'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:291:in `each_current_configuration'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:252:in `load_schema_current'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:260:in `block (3 levels) in <top (required)>'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:264:in `block (3 levels) in <top (required)>'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/MarkDiez/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:schema:load
```

**Comment by cthielen** [comment]
This may be related to the database not working from an empty set -- it began life in another project. We either accept this or generate stubs for the schema.
